spring.profiles.active: 'dev'
---
server:
  port: 1989
spring:
  data:
    neo4j:
      uri: 'http://localhost:7474'
      username: 'neo4j'
      password: 'bingo'
  profiles: 'dev'
---
server:
  port: 8080
spring:
  data:
    neo4j:
      uri: 'http://neo4j:7474'
      username: 'neo4j'
      password: 'bingo'
  profiles: 'pro'